#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs devtmpfs /dev
mv flag /root/flag
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

insmod /Carol.ko
chmod 777 /dev/carol
echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"

cat <<!

  \  |  ___|  ___|   ___|__ __| ____|
   \ |\___ \\___ \  |       |   |    
 |\  |      |     | |       |   __|  
_| \_|_____/_____/ \____|  _|  _|    
                                     

This just a demo to test your environment




!

setsid cttyhack setuidgid 1000 sh

umount /proc
umount /sys

poweroff -d 0  -f
